Update PMD4 validations to reflect current muttnik expectations (#1249)
Swirrl/pmd-rdf-validations pull request #18
Opened 2021-09-17 11:08 UTC by kieranlives

- DatasetExactlyOneContents -> DatasetMaxOneContents
- DatasetExactlyOneGraph -> DatasetMinOneGraph
- DatasetExactlyOneLabel removed
- DatasetExactlyOneTitle added
- DatasetMaxOneContributor removed
- RecordExactlyOneLabel removed

2021-09-28 10:01 UTC, RickMoynihan requested changes
Thanks for this @kieranlives.  

The changes look great, I've suggested some minor bike shedding fixes... but I'm very happy for this to be merged once they've been made.

2021-09-28 10:05 UTC, kieranlives commented on test/pmd4/swirrl/validations/pmd4/SELECT_DatasetExactlyOneTitle.ttl
> +    dct:title "I have the same title twice!" .
I wondered that! I was just following the query at this point that says `FILTER(?title1 != ?title2)` - is that similarly redundant + should I remove it as well?

2021-09-28 11:04 UTC, RickMoynihan commented on test/pmd4/swirrl/validations/pmd4/SELECT_DatasetExactlyOneTitle.ttl
> +    dct:title "I have the same title twice!" .
No it's not redundant, at least not in the same way...

this line in the sparql:

```sparql
            ?dataset dct:title ?title1, ?title2 .
```

Is just syntactic sugar for this:

```sparql
            ?dataset dct:title ?title1 .
            ?dataset dct:title ?title2 .
```

Which essentially just means bind `?title1` to the set of dataset titles, and also bind `?title2` to the set of dataset titles.  So at that point we have a table with a cartesian product in it:

  | dataset | title1 | title2 |
  | --- | --- | --- |
  | :some-ds | my title | my title | 
  | :some-ds | other title | other title |
  | :some-ds | my title | other title |
  | :some-ds | other title | my title |

So the line: 

`FILTER (?title1 != ?title2)`

then lets us convert that into:

  | dataset | title1 | title2 |
  | --- | --- | --- |
  | :some-ds | my title | other title | 

i.e. the `FILTER` is really there to stop us failing when we have just one title.

I guess we could probably remove it if we changed how the count worked.

2021-09-28 13:10 UTC, RickMoynihan requested changes

2021-11-01 16:44 UTC, RickMoynihan commented
@Robsteranium I've been through each of these and they seem good.  And I've updated @kieranlives corresponding muttnik PR so it now passes wrt IC-19.

https://github.com/Swirrl/muttnik/pull/1327

This means once that PR is merged, muttnik fixtures will be aligned with these changes.

Are there any other comments on these changes?

2021-11-16 12:32 UTC, Robsteranium commented
I've merged this in to #24.

Thanks!

2021-11-16 12:32 UTC, closed without merging